version: '3.8'
services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  ttyd:
    build: ./ttyd  # Menjalankan Dockerfile untuk ttyd dari direktori ttyd
    restart: unless-stopped
    ports:
      - '8989:8989'  # Port untuk ttyd (web-based terminal)
    environment:
      - TTYD_USER=zain
      - TTYD_PASS=password
      - TTYD_PORT=8989
