FROM alpine:3.21

# Set timezone
ENV TZ=Asia/Jakarta

# Install dependencies
RUN apk add --no-cache \
    wget \
    curl \
    nano \
    sudo \
    build-base \
    cmake \
    git \
    json-c-dev \
    zlib-dev \
    openssl-dev \
    libuv-dev \
    python3 \
    py3-pip \
    php \
    php-common \
    php-curl \
    php-zip \
    php-mbstring \
    zip \
    oniguruma-dev \
    screen \
    tzdata \
    nodejs \
    npm \
    && ln -sf /usr/share/zoneinfo/$TZ /etc/localtime

# Install pnpm globally
RUN npm install -g pnpm

# Clone Tiny File Manager and rename the main script
RUN git clone https://github.com/prasathmani/tinyfilemanager.git /opt/tinyfilemanager \
    && mv /opt/tinyfilemanager/tinyfilemanager.php /opt/tinyfilemanager/index.php

# Define users and passwords dynamically
ENV USERS="zain,user1,user2,user3,user4"
ENV PASSWORDS="pass1,pass2,pass3,pass4,pass5"
ENV START_PORT=8989

# Copy startup script
COPY ttyd/start.sh /start.sh
RUN chmod +x /start.sh

# Build and install libwebsockets from source
RUN git clone https://github.com/warmcat/libwebsockets.git /opt/libwebsockets \
    && cd /opt/libwebsockets \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && make install \
    && ldconfig \
    && rm -rf /opt/libwebsockets

# Clone and build ttyd
RUN git clone https://github.com/tsl0922/ttyd.git /opt/ttyd \
    && cd /opt/ttyd \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && make install \
    && rm -rf /opt/ttyd

# Expose ports (assuming max 10 users) + Tiny File Manager (9000)
EXPOSE 8989-8999 9000

# Run startup script to launch ttyd and Tiny File Manager
CMD ["/bin/sh", "/start.sh"]
